services:
  bot:
    build:
      context: ..
      dockerfile: ./docker/bots/Dockerfile
    image: jackcky/superpricewatchdog-bot
    ports:
      - "5000:5000"

  pipeline:
    build:
      context: ..
      dockerfile: ./docker/pipelines/Dockerfile
    image: jackcky/superpricewatchdog-pipeline
